/* (Beta) Export of data model VocabularyService of the subject dataModel.DataSpace for a PostgreSQL database. Pending translation of enumerations and multityped attributes */
CREATE TYPE VocabularyService_dataModelSpecificationType_type AS ENUM ('Vocabulary', 'Ontology', 'Application Profile', 'Data Schema');
CREATE TYPE VocabularyService_dataModelVersioning_type AS ENUM ('Semantic Versioning', 'Full History', 'None');
CREATE TYPE VocabularyService_dataspaceServiceCategory_type AS ENUM ('Federation services', 'Participant Agent services', 'Value Creation services');
CREATE TYPE VocabularyService_type AS ENUM ('VocabularyService');
CREATE TABLE VocabularyService (
  "additionalBuildingBlock" JSON,
  "additionalBuildingBlockDescription" JSON,
  "businessOfferings" JSON,
  "dataModelDomain" JSON,
  "dataModelSpecificationType" VocabularyService_dataModelSpecificationType_type,
  "dataModelVersioning" VocabularyService_dataModelVersioning_type,
  "dataspaceBuildingBlock" JSON,
  "dataspaceProductPurpose" TEXT,
  "dataspaceService" JSON,
  "dataspaceServiceCategory" VocabularyService_dataspaceServiceCategory_type,
  "dependencies" JSON,
  "deploymentsInOperation" JSON,
  "description" TEXT,
  "documentation" JSON,
  "domain" JSON,
  "exportFormats" JSON,
  "functionalApplicationArea" JSON,
  "geographicalApplicationArea" JSON,
  "governanceFeatures" TEXT,
  "hasVersion" TEXT,
  "id" TEXT PRIMARY KEY,
  "image" JSON,
  "importFormats" JSON,
  "keywords" JSON,
  "license" JSON,
  "licenseDeclared" JSON,
  "maintainer" JSON,
  "mappingFunctionalities" TEXT,
  "publicationAccessibility" JSON,
  "referenceDatasetManagement" TEXT,
  "similarTools" JSON,
  "supportedStandards" JSON,
  "supportedSyntaxes" JSON,
  "supportingAttachments" JSON,
  "technologyReadinessLevel" NUMERIC,
  "title" TEXT,
  "trlJustification" TEXT,
  "type" VocabularyService_type,
  "url" TEXT,
  "validationCapabilities" JSON
);